### ISSUE TITLE
patterns.h creates segmentation fault

### ISSUE THREAD

**Issue by songyang-dev** [songyang-dev/comp520-peephole#5]
Do `./clean.sh` and `./count.sh` after. You will see the compiler warnings and the segmentation faults before each optimization attempt. Because of this, we have 0% improvement.

**Comment by XsongyangX** [comment]
It is probably because of your `replace` calls. And maybe because you don't return the return value of replace.

**Comment by XsongyangX** [comment]
I commented out your pattern for now.

**Comment by charlesgingras** [comment]
I talked with Alex about it yesterday and he said it definitely is a sound pattern.
So the issue must be with how its implemented.
Right I just have other things that are taking priority over this.
